name: Update GitHub Stats

on:
  schedule:
    - cron: "0 0 * * *"  # every day at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Update README
        uses: actions/checkout@v3

      - name: Auto Commit README
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git commit --allow-empty -m "Update README stats"
          git push
