name: Update GitHub Stats

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight
  workflow_dispatch:     # Allows manual triggering

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate GitHub Stats SVG
        uses: sammekg/github-readme-stats@master
        with:
          username: SammekG

      - name: Commit & Push Changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add README.md
          git commit -m "📊 Update GitHub stats [auto]" || echo "No changes to commit"
          git push
